car: Disable the optimazation of System Server in phone_car.
- The optimazation removes the unused hidden apis in System Server,
  which can cause NoSuchMethodError exception on the access from
  CarServiceHelperService.

Bug: 259601271
Test: build phone_car and check if it boots.
Change-Id: I8e5c5e6b461c55559b147e90b83e798bc6e563d3