car: Switch to audiocontrol AIDL HAL
ERROR: files are incompatible: android.hardware.automotive.audiocontrol@2.0::IAudioControl/default is deprecated in compatibility matrix at FCM Version 7; it should not be served.
    because it matches android.hardware.automotive.audiocontrol@2.0::IAudioControl/default from /system/etc/vintf/compatibility_matrix.5.xml
The following instances are in the device manifest but not specified in framework compatibility matrix:
    android.hardware.automotive.audiocontrol@2.0::IAudioControl/default

Change-Id: I97b4f1283a370f93f516ca67574656c99b29649d