car: Switch to vehicle AIDL HAL V4
ERROR: files are incompatible: android.hardware.automotive.vehicle@2.0::IVehicle/default is deprecated in compatibility matrix at FCM Version 202404; it should not be served.
    because it matches android.hardware.automotive.vehicle@2.0::IVehicle/default from /system/etc/vintf/compatibility_matrix.6.xml

Change-Id: If0774cbd8e9015973717ccfbcfdeb7f0c9ea6297